# image: python:3.6-alpine
variables:
  reposerver: '172.27.26.5'
  repobasepath: '/5_workspace/repos/'
pages:
  stage: deploy
  script:
  - pip install --user sphinx
  - pip install --user sphinx_rtd_theme
  - pip install --user recommonmark
  - sphinx-build sphinx_documentation/source/ _build/html
  - mv _build/html public
  artifacts:
    paths:
      - public
  only:
  - master
downloadrepo:
  stage: test
  script:
    - ssh -t gitlabrunner@$reposerver "cd $repobasepath"
  only:
    - master
test_variable:
  stage: test
  script:
    - echo $CI_JOB_STAGE