# image: python:3.6-alpine
variables:
  reposerver: '172.27.26.5'
  repobasepath: '/5_workspace/repos/'
  MASTER_PATH: /5_workspace/docker/pavian_docker
  DEV_PATH: /5_workspace/docker/pavian_docker_dev
  DOCKER_SERVER: prod-01.airflow.naktuinbouw.cloud

pages:
  stage: deploy
  script:
    - python -m pip install --user sphinx
    - python -m pip install --user sphinx_rtd_theme
    - python -m pip install --user recommonmark
    - sphinx-build sphinx_documentation/source/ _build/html
    - mv _build/html public
  artifacts:
    paths:
      - public
  only:
  - master

dev:
  stage:
    build
  script:
    - eval $(keychain --eval id_rsa_airflow)
    # this part must be done from prod!
    - >
      ssh airflow@$reposerver
      "cd $DEV_PATH &&
      git reset --hard && 
      git checkout $CI_COMMIT_REF_NAME &&
      git pull &&
      cat dev.env > .env"
    - if [[ $? != 0 ]]; then exit $?; fi
    - >
      ssh airflow@$DOCKER_SERVER
      "cd $DEV_PATH;
      docker-compose -p pavian_docker_dev down -v;
      docker-compose -p pavian_docker_dev up -d"
    - if [[ $? != 0 ]]; then exit $?; fi
  except:
    - master


rebuild_docker:
  stage:
    build
  script:
    - eval $(keychain --eval id_rsa_airflow)
    - >
      ssh airflow@$reposerver
      "cd $DEV_PATH &&
      docker-compose build --build-arg SSH_PRIVATE_KEY="$(cat /home/aroe/.ssh/id_rsa)
      --build-arg SSH_PUBLIC_KEY="$(cat /home/aroe/.ssh/id_rsa.pub)" --build-arg CACHE_DATE=$(date +%s)"
    - if [[ $? != 0 ]]; then exit $?; fi
  only:
    refs:
      - dev
    changes:
      - /services/*/Dockerfile
      - docker-compose.yml
      - dev.env

prod:
  stage:
    build
  script:
    - eval $(keychain --eval id_rsa_airflow)
    - >
      ssh airflow@$reposerver
      "cd $MASTER_PATH &&
      git reset --hard &&
      git checkout master &&
      git pull &&
      cat env > .env"
    - if [[ $? != 0 ]]; then exit $?; fi
    - >
      ssh airflow@$DOCKER_SERVER
      "cd $MASTER_PATH;
      docker-compose -p pavian_docker_dev down -v;
      docker-compose -p pavian_docker_dev up -d"
    - if [[ $? != 0 ]]; then exit $?; fi
  only:
    - master