version: '3.4'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile.prod
      args:
        - BLAST_VERSION=${BLAST_VERSION}
    command: gunicorn --bind 0.0.0.0:5000 manage:app --timeout 300
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
      - ${PAVIAN_IN_H}:/pavian/in:ro
      - ${PAVIAN_OUT_H}:/pavian/out
      - ${TAXA_SQLITE_H}:/pavian/taxa.sqlite
      - ${TAXA_SQLITE_PKL_H}:/pavian/taxa.sqlite.traverse.pkl
      - ${BLASTDB_NT_H}:/blast_db/nt
      - ${BLASTDB_REFSEQ_H}:/blast_db/refseq
    expose:
      - 5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    ports:
      - 1337:80
    depends_on:
      - web
  jbrowse:
    build: ./services/jbrowse
    volumes:
      - ${PAVIAN_OUT_H}:/jbrowse/data/pavianfiles
    ports:
      - 5004:5004
  pavian:
    build:
      context: ./services/pavian
      args:
        - BRANCH=master
    volumes:
      - ${PAVIAN_IN_H}:/pavian/in:ro
    ports:
      - 3838:3838
    env_file:
      - ./.env.prod
      - ./.env.prod.db

volumes:
  postgres_data:
  static_volume:
  media_volume: