version: '3.7'

services:
  web:
    build:
      context: ./services/web
      args:
        - BLAST_VERSION=${BLAST_VERSION}
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
      - ${PAVIAN_IN_H}:/pavian/in:ro
      - ${PAVIAN_OUT_H}:/pavian/out
      - ${TAXA_SQLITE_H}:/pavian/taxa.sqlite
      - ${TAXA_SQLITE_PKL_H}:/pavian/taxa.sqlite.traverse.pkl
      - ${BLASTDB_NT_H}:/blast_db/nt
      - ${BLASTDB_REFSEQ_H}:/blast_db/refseq
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=project/__init__.py
      - BLASTDB_NT=/blast_db/nt/nt
      - BLASTDB_REFSEQ=/blast_db/refseq/refseq_genomic
      - PAVIAN_IN=/pavian/in
      - PAVIAN_OUT=/pavian/out
      - TAXA_SQLITE=/pavian/taxa.sqlite
      - TAXA_SQLITE_PKL=/pavian/taxa.sqlite.traverse.pkl
      - SQL_HOST=${SQL_HOST_ENV}
      - SQL_PORT=${SQL_PORT_ENV}
      - HOST_IP=${HOST_IP_ENV}
      - JBROWSE_PORT=${JBROWSE_PORT_ENV}
      - FLASK_PORT=${FLASK_PORT_ENV}
      - DATABASE_URL=postgresql://${POSTGRES_USER_ENV}:${POSTGRES_PASSWORD_ENV}@${SQL_HOST_ENV}:${SQL_PORT_ENV}/${POSTGRES_DB_DEV_ENV}
    # Depends on db, because tables Classes are created in __init__.py
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ENV}
      - POSTGRES_DB=${POSTGRES_DB_DEV_ENV}
  jbrowse:
    build: ./services/jbrowse
    volumes:
      - ${PAVIAN_OUT_H}:/jbrowse/data/pavianfiles
    ports:
      - 5004:5004
  pavian:
    build:
      context: ./services/pavian
      args:
        - BRANCH=dev
    volumes:
      - ${PAVIAN_IN_H}:/pavian/in:ro
    ports:
      - 3838:3838
#    secrets:
#      - db-user
#      - db-pass
    environment:
      - PAVIAN_IN=/pavian/in
      - SQL_HOST=${SQL_HOST_ENV}
      - HOST_IP=${HOST_IP_ENV}
      - FLASK_PORT=${FLASK_PORT_ENV}
      - POSTGRES_USER=${POSTGRES_USER_ENV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_ENV}
      - POSTGRES_DB=${POSTGRES_DB_DEV_ENV}
#      - POSTGRES_USER={{DOCKER-SECRET:db-user}}
#      - POSTGRES_PASSWORD={{DOCKER-SECRET:db-pass}}

#secrets:
#  db-user:
#    external: true
#  db-pass:
#    external: true

volumes:
  postgres_data: